title: "Vector Forge: seamless transformation of Data into Vectors"
description: "Vector Forge opens up a world of effortless vectorization, enabling you to transform text and images into high-dimensional vectors using Machine Leading models. With a focus on simplicity and efficiency."
tagline: "Crafting Vectors, Simplified"
url: "https://www.vector-forge.com/"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

logo: /assets/logo.png

social:
  name: Simeon Emanuilov
  links:
    - https://www.linkedin.com/in/simeon-emanuilov/
    - https://github.com/simeonemanuilov
